---

- include_vars: "{{ansible_distribution}}.yml"

- name: Install dependencies
  apt:
    pkg: "{{ backup_apt_dependencies }}"

- set_fact: backup_duplicity_pkg="{{backup_duplicity_pkg}}={{backup_duplicity_version}}"
  when: backup_duplicity_version|bool

- name: Install duplicity
  apt: pkg={{backup_duplicity_pkg}}
